; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "RDC EUART Driver"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "RDC, Inc."
!define PRODUCT_WEB_SITE "http://www.rdc.com.tw"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\devcon.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

SetCompressor lzma

; MUI 1.67 compatible ------
!include "MUI.nsh"
!include "WinVer.nsh"
!include "x64.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
;!insertmacro MUI_PAGE_LICENSE "c:\path\to\licence\YourSoftwareLicence.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
;!define MUI_FINISHPAGE_RUN ""
;!define MUI_FINISHPAGE_RUN_PARAMETERS ""
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"
#!insertmacro MUI_LANGUAGE "TradChinese"

LangString UNINSTALL_CONFIRM ${LANG_ENGLISH} "Thank you very much! $(^Name) has been successfully removed."
LangString UNINSTALL_CONFIRM ${LANG_SIMPCHINESE} "非常感謝您的使用！ $(^Name) 已成功地从您的计算机中移除。"

LangString UNINSTALL_DETECTS_PROMPT ${LANG_ENGLISH} "The machine detects the already installed"
LangString UNINSTALL_DETECTS_PROMPT ${LANG_SIMPCHINESE} "检测到本机已经安装了"

LangString UNINSTALL_PROMPT ${LANG_ENGLISH} "Whether to uninstall the installed version?"
LangString UNINSTALL_PROMPT ${LANG_SIMPCHINESE} "是否先卸载已安装的版本？"

LangString REMOVE_COMPONENT ${LANG_ENGLISH} "You sure you want to completely remove $ (^ Name), and all of its components?"
LangString REMOVE_COMPONENT ${LANG_SIMPCHINESE} "你确实要完全移除 $(^Name) ，其及所有的组件？"

; Reserve files
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\${PRODUCT_NAME}"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Var UNINSTALL_PROG
Var OLD_VER
Var OLD_PATH
Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY

  ClearErrors
   ReadRegStr $UNINSTALL_PROG ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString"
   IfErrors  done

   ReadRegStr $OLD_VER ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion"
   MessageBox MB_YESNOCANCEL|MB_ICONQUESTION \
     "$(UNINSTALL_DETECTS_PROMPT) ${PRODUCT_NAME} $OLD_VER。\
     $\n$\n$(UNINSTALL_PROMPT)" \
       /SD IDYES \
       IDYES uninstall \
       IDNO done
   Abort

 uninstall:
   StrCpy $OLD_PATH $UNINSTALL_PROG -10


   ExecWait '"$UNINSTALL_PROG" /S _?=$OLD_PATH' $0
   DetailPrint "uninst.exe returned $0"
   Delete "$UNINSTALL_PROG"
   RMDir $OLD_PATH


 done:
FunctionEnd

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite try
  ${If} ${IsWinXP}
      ${If} ${RunningX64}
            File /r "RDC EUART Driver\Rinf_WinXPx64\*.*"
      ${Else}
            File /r "RDC EUART Driver\Rinf_WinXPx86\*.*"
      ${EndIf}
  ${EndIf}

  ${If} ${AtLeastWinVista}
      ${If} ${RunningX64}
            File /r "RDC EUART Driver\Rinf_WinVistaAndLaterx64\*.*"
      ${Else}
            File /r "RDC EUART Driver\Rinf_WinVistaAndLaterx86\*.*"
      ${EndIf}
   ${EndIf}

  ${If} ${IsWin2003}
      ${If} ${RunningX64}
            File /r "RDC EUART Driver\Rinf_WinS03x64\*.*"
      ${Else}
            File /r "RDC EUART Driver\Rinf_WinS03x86\*.*"
      ${EndIf}
  ${EndIf}
  DetailPrint "Exec InstallDriverPackage.bat ......"
  nsExec::Exec '$INSTDIR\InstallDriverPackage.bat'
  #ExecWait '$INSTDIR\InstallDriverPackage.bat'
  DetailPrint "some program returned $0"
SectionEnd

Section -AdditionalIcons
  CreateDirectory "$SMPROGRAMS\${PRODUCT_NAME}"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\devcon.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\devcon.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(UNINSTALL_CONFIRM)"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "$(REMOVE_COMPONENT)" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  DetailPrint "Exec UninstallDriverPackage.bat ......"
  SetOutPath "$INSTDIR"
  nsExec::Exec '$INSTDIR\UninstallDriverPackage.bat'
  #ExecWait '$INSTDIR\UninstallDriverPackage.bat'

  RMDir /r "$SMPROGRAMS\${PRODUCT_NAME}"
  SetOutPath "$SMPROGRAMS"
  RMDir /r "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd